work_dir: ./output_gb/ctrgcn_V1_B_3D

# feeder
feeder: dataset.feeder_xyz.Feeder
train_feeder_args: 
  data_path: dataset/save_3d_pose/train_joint.npz
  data_split: train
  p_interval: [0.5, 1]
  window_size: -1
  bone: True
  vel: False

test_feeder_args:
  data_path: ./dataset/save_3d_pose_B/test_joint_B.npz
  data_split: test
  p_interval: [0.95]
  window_size: -1
  bone: True
  vel: False

# model
model: model.ctrgcn_xyz.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.2
lr_decay_rate: 0.1
step: [70, 80]
warm_up_epoch: 5

# training
device: 0
batch_size: 32
test_batch_size: 32
num_epoch: 100
nesterov: True
